### ISSUE TITLE
Will there be a Python Version?

### ISSUE THREAD

**Issue by davidjeba** [riggraz/astuto#103]
Finding ruby developers is a nightmare [atleast in my city]
every 1 in 5 developers know python

will there be a python edition?
or a package for django/wagtail?

**Comment by riggraz** [comment]
Hi davidjeba, thanks for the interest in the project!

Unfortunately there won't be a Python version, since it would take forever to rewrite Astuto from scratch in another language. Python would probably result in more people being able to contribute, but that's not enough to justify an entire rewriting. Hope you understand!

Have a nice day, bye 👋🏻
