### ISSUE TITLE
amazing project

### ISSUE THREAD

**Issue by ImaCrea** [riggraz/astuto#34]
no more to say 💎

**Comment by pierreozoux** [comment]
Looks really nice indeed!

Do you have a business model in mind?  Or what is the motivation to develop and open source it? Looks like you didn't commit much lately ?

Hope you are doing fine, be careful of the burn out, the biggest disease of OpenSource maintainers :) Take care!

Cheers!

**Comment by riggraz** [comment]
Thanks for the support guys.

> Do you have a business model in mind? Or what is the motivation to develop and open source it? Looks like you didn't commit much lately ?

I originally developed Astuto for my bachelor degree in Computer Engineering, then decided to open source it because why not. However, after releasing it, I was pretty tired on working on it, that's why I haven't commited much lately.

Anyway, lately motivation has come back again, so I'm getting back to work! I'll hopefully see you around this repo in the future :)

Cheers
